#!/usr/bin/env bash

set -e

SKIP_INSTALL=0
INSTALL_ENV=
ENV_SOURCE=

if [ -f /etc/lsb-release ]; then 
	source /etc/lsb-release
	if [ -n $DISTRIB_ID ]; then
		INSTALL_ENV=${DISTRIB_ID,,}
		ENV_SOURCE="lsb-release"
	fi
fi
if [ -f /etc/os-release ]; then
	source /etc/os-release
	if [ -n $ID ]; then 
		INSTALL_ENV=${ID,,}
		ENV_SOURCE="os-release"
	fi
fi

# TODO: fix ubuntu <=> debian mapping
case $INSTALL_ENV in
*ubuntu*)
	INSTALL_ENV=debian
	;;
esac

while getopts "nd:" opt; do
  case $opt in
    n)
		SKIP_INSTALL=1
		;;
	d)
		INSTALL_ENV=$OPTARG
		ENV_SOURCE=cli
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		exit 1
		;;
	:)
		echo "Option -$OPTARG requires an argument." >&2
		exit 1
		;;
	esac
done

if [ -z $INSTALL_ENV ]; then
	SKIP_INSTALL=1
fi

if [ $SKIP_INSTALL -eq 0 ]; then
	echo "Trying install environment <$INSTALL_ENV>, detected from <$ENV_SOURCE>"
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

if [ $SKIP_INSTALL -eq 0 ]; then
	if [ ! -f ${BASEDIR}/distro/${INSTALL_ENV}.${CONFIG} ]; then
		echo "!! failed to find install script, skipping !!"
	else 
		if sudo -v >/dev/null 2>/dev/null; then
			"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "distro/${INSTALL_ENV}.${CONFIG}"
		fi
	fi
fi
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"

# change default shell to zsh
nvim -es -c "PlugInstall|q|q"
sudo chsh -s /usr/bin/zsh $USER >/dev/null 2>/dev/null
