#!/usr/bin/env bash

set -e

# make sure we are on a debian like system
SKIP_INSTALL=1

if [ -f /etc/debian_version ]; then
        SKIP_INSTALL=0
fi
while getopts "n" opt; do
  case $opt in
    n)
      SKIP_INSTALL=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done



CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

if [ $SKIP_INSTALL -eq 0 ]; then
	if sudo -v >/dev/null 2>/dev/null; then
		"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "root.${CONFIG}"
	fi
fi
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"

# change default shell to zsh
nvim -es -c "PlugInstall|q|q"
sudo chsh -s /usr/bin/zsh $USER >/dev/null 2>/dev/null
