#!/bin/sh

set -eu

yadm=$(dirname "$0")
cd "$yadm"

. "$yadm"/functions.sh

install_package yadm transcrypt neovim eza pet fish nerdfetch

yadm transcrypt -i me@kurabloodlust.eu
chsh -s "$( env fish )"
