#!/bin/sh

set -eu

yadm=$(dirname "$0")
cd "$yadm"

read -p "Do you want to run system bootstrap? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    curl -Ssf https://pkgx.sh | sh -s -- uvx --from ansible-core --with ansible ansible-playbook -c local -i localhost, --ask-become-pass playbook.yml
fi

. "$HOME"/.profile

yadm decrypt
yadm remote set-url origin git@github.com:cking/dotfiles.git

echo "Changing shell to fish..."
fish=$( grep fish /etc/shells | head -n1 )
if [ "$fish" = "" ]; then
	echo " - Adding fish to /etc/shells"
	fish=$( command -v fish )
	echo $fish | _sudo tee -a /etc/shells > /dev/null
fi
chsh -s "$fish"
